### ISSUE TITLE
SBOM分析里，镜像检测结果详情列表显示字段不全

### ISSUE THREAD

**Issue by maguohao2017** [HummerRisk/HummerRisk#100]
**HummerRisk 版本**
v0.3.2

**运行方式(安装包运行 or 源码运行 ?)**

**浏览器版本**

**严重程度（高、中、低）**
低

**Bug 描述**
SBOM分析里，镜像检测结果详情列表显示字段不全

**Bug 重现步骤(有截图更好)**
SBOM分析里，镜像检测结果详情列表显示字段不全

**Comment by harris1943** [comment]
已解决
