### ISSUE TITLE
源码检测、镜像检测编辑页面，版本字段下拉列表显示错乱

### ISSUE THREAD

**Issue by maguohao2017** [HummerRisk/HummerRisk#131]
**HummerRisk 版本**
v0.4.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌浏览器

**严重程度（高、中、低）**
低

**Bug 描述**
源码检测、镜像检测编辑页面，版本字段下拉列表显示错乱。

**Bug 重现步骤(有截图更好)**
<img width="1509" alt="image" src="https://user-images.githubusercontent.com/43598049/195632665-c4bd1f1e-6d6c-4131-9b57-bbfc0337d3a3.png">

**Comment by harris1943** [comment]
已修复
