### ISSUE TITLE
华为云保存、校验失败

### ISSUE THREAD

**Issue by maguohao2017** [HummerRisk/HummerRisk#132]
**HummerRisk 版本**
v.0.4.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌浏览器

**严重程度（高、中、低）**
高

**Bug 描述**
华为云保存、校验失败

**Bug 重现步骤(有截图更好)**
<img width="1316" alt="image" src="https://user-images.githubusercontent.com/43598049/195632270-187c5cfc-fb89-4ae1-82f6-9e679e78d6c3.png">

**Comment by harris1943** [comment]
已修复
