### ISSUE TITLE
添加主机时选择凭据没反应

### ISSUE THREAD

**Issue by rainbowdush** [HummerRisk/HummerRisk#139]
**HummerRisk 版本**
v0.4.1

**运行方式(安装包运行 or 源码运行 ?)**

安装包运行
**浏览器版本**
chrome  106.0.5249.103

**严重程度（高、中、低）**

**Bug 描述**
主机检测，添加主机的时候，选择凭证似乎不行。

**Bug 重现步骤(有截图更好)**
1. 在主机检测里我想添加一台主机，输入了基本信息
![image](https://user-images.githubusercontent.com/107109637/197572304-885d3b79-10fd-418c-829d-5eaf010c1fbb.png)

2.密钥选择了已经建好的一个密钥
![image](https://user-images.githubusercontent.com/107109637/197572184-c5bc5557-338f-4751-92b0-f4c606f9d268.png)

3.列表里还是显示没有选择
![image](https://user-images.githubusercontent.com/107109637/197573344-5bef71bc-4900-4d74-8419-3009830bfc8d.png)

**Comment by harris1943** [comment]
已完成
