### ISSUE TITLE
资源态势里腾讯云CVM的信息没有显示

### ISSUE THREAD

**Issue by rainbowdush** [HummerRisk/HummerRisk#140]
**HummerRisk 版本**
V0.4.1

**运行方式(安装包运行 or 源码运行 ?)**

安装包运行

**Bug 描述**
资源态势同步之后，腾讯云的没有显示CVM的信息

**Bug 重现步骤(有截图更好)**
绑定了一个腾讯云的账号。
建了一个同步任务，能看到同步了一份的数据，但是不全，CVM的数据就没有。

**Comment by harris1943** [comment]
已处理
