### ISSUE TITLE
k8s

### ISSUE THREAD

**Issue by Admini521** [HummerRisk/HummerRisk#149]
**HummerRisk 版本**
v0.5

**运行方式(安装包运行 or 源码运行 ?)**

k8s
**浏览器版本**
chrom 360 IE

**严重程度（高、中、低）**
高

**Bug 描述**
1.检测镜像扫描异常
2.镜像名称限制2-50字符不能更改
**Bug 重现步骤(有截图更好)**
1.
![{ff13d555-28e2-4a79-a8f6-099b390801df}](https://user-images.githubusercontent.com/55176505/200531747-3cb2c47c-5b62-4d9c-ba45-2f53ca4703f6.png)
![{6976f054-8da4-46bf-afb9-fdb97cf3d0dd}](https://user-images.githubusercontent.com/55176505/200531807-3167bf0f-ce2d-4891-a32c-988fd8b78302.png)
![{81f9a26c-369b-4572-a888-bb5884aec601}](https://user-images.githubusercontent.com/55176505/200531849-fd3c0efb-a69f-41bc-bac1-18ab7e88bb93.png)
![{2d9a6982-ecc9-4dd2-adbe-a4889db69490}](https://user-images.githubusercontent.com/55176505/200532267-76af30a9-d93e-4851-888e-2d891e8c552f.png)

2.建议检测报告生产后pdf和html例如主机检测和k8s等
3.官网安装环境指导部署要详细图文教程指引

**Comment by harris1943** [comment]
新增pdf导出功能。
安装知道部署视频：https://www.bilibili.com/video/BV1JK411d79A/?spm_id_from=333.337.search-card.all.click&vd_source=4fbdae7a84541c5918ecbb52da1569dc
