### ISSUE TITLE
云资源同步不到腾讯云的虚拟机

### ISSUE THREAD

**Issue by colinn66** [HummerRisk/HummerRisk#154]
**HummerRisk 版本**
v0.5.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**

云资源同步，居然没有虚拟机的信息，把最基本的给忽略了。

**Bug 重现步骤(有截图更好)**
1. 在云资源态势里同步了腾讯云的资源，但是现实出来的内容里没有虚拟机信息。
2.
3.

**Comment by harris1943** [comment]
已完成
