### ISSUE TITLE
k8s资源拓扑，选择了风险等级后应该可以清除

### ISSUE THREAD

**Issue by colinn66** [HummerRisk/HummerRisk#171]
K8s资源拓扑里面，k8s风险视角，选择风险的等级后，没法取消选择，重新查看全部内容。

![2244FBC4-2E4D-447C-94E1-53392C4F238E](https://user-images.githubusercontent.com/107197811/205285128-90a59e77-099e-4285-b0ad-ff1ae3aa778b.png)

建议仅把有漏洞的镜像前面显示红色图标，其他的显示白色图标

![9CBBF9B1-E6D3-43EA-ADA6-5EA357C09597](https://user-images.githubusercontent.com/107197811/205285271-fdaf8de6-61ac-4f07-a624-92d10df24747.png)

**Comment by harris1943** [comment]
<img width="174" alt="image" src="https://user-images.githubusercontent.com/105598469/205437007-cb01e515-57ad-4f97-833c-bc50164cd956.png">
点击存在风险的资源就可以清除选中项，我再单独加一个清除按钮吧

**Comment by colinn66** [comment]
ok，确认可以了，关闭issue了
