### ISSUE TITLE
部署检测中检测的文件有错误

### ISSUE THREAD

**Issue by colinn66** [HummerRisk/HummerRisk#174]
**Bug 描述**
部署检测中，我选择的是123这个yaml，是检测结果里，检测的事trivy.yaml
所以实际并没有检测我创建的这个问题，应该是有问题。
请参考下图。

![B759161B-D252-4B3D-9A1B-1D804C9EAC81](https://user-images.githubusercontent.com/107197811/205286329-302650df-3187-4873-802e-90dc7ae5efd5.png)
![04876D2B-0DC6-446F-9856-F08023A8DBDD](https://user-images.githubusercontent.com/107197811/205286345-6cf04c62-e036-4f25-b28e-cc7c81c637dd.png)

**Comment by harris1943** [comment]
这里因为是有中文名称的情况，所以统一用trivy.yaml当做检测文件名，所有的检测都叫这个名，可以改成deploy.yaml或者其他的，讨论一下，这个检测功能是没问题的。

**Comment by colinn66** [comment]
现在可以正常执行了
