### ISSUE TITLE
首页分析筛选功能无法正常工作

### ISSUE THREAD

**Issue by alvin5840** [HummerRisk/HummerRisk#178]
**HummerRisk 版本**
v0.6.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome

**严重程度（高、中、低）**
中

**Bug 描述**
1. 选择完一个筛选规则后，其他筛选无法使用
<img width="1507" alt="image" src="https://user-images.githubusercontent.com/107904113/205320024-62693742-a001-405b-a827-c672f72baf40.png">

2. 按风险登记筛选无法使用，应该是没有字段可以去匹配这一项
<img width="992" alt="image" src="https://user-images.githubusercontent.com/107904113/205320916-3f6fbc2a-3acd-42db-a4d7-80c51b3700ce.png">

**Bug 重现步骤(有截图更好)**
1. 按测试人员筛选-选择 admin
2. 点击按分组筛选，不论是按规则标签筛选还是按风险条例筛选都失效

这个筛选规则是叠加筛选，还是覆盖筛选?

**Comment by harris1943** [comment]
筛选规则是叠加，规则分组暂时未使用，先删除了吧。
