### ISSUE TITLE
对象存储创建青云存储桶报错

### ISSUE THREAD

**Issue by harris1943** [HummerRisk/HummerRisk#203]
**HummerRisk 版本**
v0.6.0

**运行方式(安装包运行 or 源码运行 ?)**

**浏览器版本**

**严重程度（高、中、低）**

**Bug 描述**
对象存储创建青云存储桶报错

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/105598469/205752418-27614d96-1225-4492-97a4-014469f5a9de.png)

**Comment by harris1943** [comment]
还有权限没有获取到，都是空的。示例按照阿里云和腾讯云为标准参考。

**Comment by jackie066** [comment]
青云创建bucket sdk 有问题，返回存储桶不存在
sdk 文档 https://docsv3.qingcloud.com/storage/object-storage/sdk/java/
