### ISSUE TITLE
镜像管理>镜像列表中的状态显示有问题

### ISSUE THREAD

**Issue by colin022** [HummerRisk/HummerRisk#26]
**HummerRisk 版本**
0.2.2

**运行方式(安装包运行 or 源码运行 ?)**

安装包运行

**浏览器版本**
Chrome

**Bug 描述**
我在镜像管理中添加镜像时填错了信息，但是镜像列表中，状态还是显示为正常

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by harris1943** [comment]
已解决
