### ISSUE TITLE
镜像检测中扫描结果excel导出

### ISSUE THREAD

**Issue by Ling-Huang-Get** [HummerRisk/HummerRisk#260]
**HummerRisk 版本**
 v0.6.0

**你希望我们怎样改进？**
云原生安全->镜像检测中漏洞扫描结果excel导出

**Comment by harris1943** [comment]
升级到v0.7.0以后，就可以导出json/pdf或excel了。
<img width="1507" alt="image" src="https://user-images.githubusercontent.com/105598469/212469958-d4674766-f1e8-44fe-a014-90bfc2a56461.png">
