### ISSUE TITLE
镜像检测处点击登录国家信息安全漏洞库，查询检测出的漏洞显示403

### ISSUE THREAD

**Issue by Ling-Huang-Get** [HummerRisk/HummerRisk#261]

**Comment by harris1943** [comment]
这个网站的详情地址后缀总是变幻，我们这边已经修改了，以后直接指向总域名：https://www.cnnvd.org.cn/。手动点击漏洞信息即可。
<img width="1509" alt="image" src="https://user-images.githubusercontent.com/105598469/212469904-fdb01579-ed52-465a-a17b-6bcffc98627e.png">
