### ISSUE TITLE
镜像结果导出会出现重复结果两次

### ISSUE THREAD

**Issue by Ling-Huang-Get** [HummerRisk/HummerRisk#267]
**HummerRisk 版本**
v0.8.0

**Bug 重现步骤(有截图更好)**
1.点进某个镜像检测结果，在详情列表下载导出excel，发现excel表格中重复漏洞详情
2.图片上传不上去

**Comment by harris1943** [comment]
问题1：这个导出数据是根据页面来的，正常页面的数据多少条导出多少条，您说的重复是怎么样的重复，可以截图或者描述一下吗。
<img width="1406" alt="image" src="https://user-images.githubusercontent.com/105598469/212666060-3a5295f5-802d-4843-95f8-c8d38d8ab03f.png">

<img width="1289" alt="image" src="https://user-images.githubusercontent.com/105598469/212666128-b4395540-4f7a-4b69-a8a8-76d354d7073e.png">

**Comment by Ling-Huang-Get** [comment]
![1](https://user-images.githubusercontent.com/62459923/212819168-b4ea904b-ef05-4066-929f-812776c0698b.png)
