### ISSUE TITLE
【云原生安全】需求：添加镜像仓库的验证

### ISSUE THREAD

**Issue by alvin5840** [HummerRisk/HummerRisk#27]
**HummerRisk 版本**
v0.2.3

**你希望我们怎样改进？**
如图：建议添加镜像仓库的校验，并且镜像仓库需要我填写的信息不够明确，例如仓库地址：https还是http，domain还是ip？是不是都可以？
<img width="1486" alt="image" src="https://user-images.githubusercontent.com/107904113/187444499-2613a32e-4118-4ad5-9b66-6af86ac32c35.png">

**你的思路建议是什么？**
添加必填信息的提示，添加仓库校验按钮

**Comment by harris1943** [comment]
现在可以添加镜像仓库地址https://xxx，并且可以自动获取镜像列表。
