### ISSUE TITLE
镜像检测一直在处理中

### ISSUE THREAD

**Issue by harold5384** [HummerRisk/HummerRisk#274]
**HummerRisk 版本**
v0.9.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome

**严重程度（高、中、低）**
中

**Bug 描述**
使用对aws ecr仓库的镜像执行镜像扫描，一直在处理中，重试无效，没有看到相应日志
<img width="1287" alt="image" src="https://user-images.githubusercontent.com/117808901/215258354-44ade9ec-ddd5-4818-87c8-239bdd8cf5fe.png">

**Bug 重现步骤(有截图更好)**
1. 创建镜像，镜像地址使用： public.ecr.aws/c5s0o3x5/hummerrisk:v0.9.0
<img width="905" alt="image" src="https://user-images.githubusercontent.com/117808901/215258459-1be45d42-7499-4b7b-ae6d-89f654e0caf8.png">

2. 对该镜像执行扫描

**Comment by harris1943** [comment]
镜像太大了导致的，hummerrisk v0.9.0 有 2.84GB。我这边用命令行手动执行检测也有点慢，拉镜像和检测镜像都需要点时间，还有您的环境可能需要手动更新一下漏洞库。

**Comment by harris1943** [comment]
漏洞库使用v2版本。页面的检测设置需要将跳过数据库更新设置成true，不然每次检测会先去更新漏洞库，github网络很慢，导致阻塞。
<img width="1096" alt="image" src="https://user-images.githubusercontent.com/105598469/219064435-852d5c04-db08-4752-b7b6-3647849502d8.png">
