### ISSUE TITLE
离线更新漏洞库-上传文件报错

### ISSUE THREAD

**Issue by paddy235** [HummerRisk/HummerRisk#277]
**HummerRisk 版本**

0.9.0

**运行方式(安装包运行 or 源码运行 ?)**

内网环境，离线安装

**浏览器版本**

Chromium 版本 99.0.4844.84（正式版本）Fedora Project （64 位）

**严重程度（高、中、低）**

高

**Bug 描述**

将离线库上传点击确定报 

```json

{ "timestamp": 1675216341374, "status": 500, "error": "Internal Server Error", "path": "/system/updateVulnDbOffline" }


```

**Bug 重现步骤(有截图更好)**
1. 
2.
3.

**Comment by paddy235** [comment]
![Uploading ksnip_20230201-094834.png…]()

**Comment by harris1943** [comment]
v0.10.0以后版本删除此功能
