### ISSUE TITLE
【软件安全】软件依赖检查结果优化

### ISSUE THREAD

**Issue by alvin5840** [HummerRisk/HummerRisk#28]
**HummerRisk 版本**
v0.2.2

**你希望我们怎样改进？**
1. 目前检测结果太不直观，建议通过表、或者图的方式做一个可视化展示，有助于我们更轻松的进行依赖包问题分析
2. 整个检查过程的连贯性不强，不是很顺手，比如：软件包导入后，可以对软件包右击进行检测，同样检测完应该点击某个软件包查看检测结果

<img width="1478" alt="image" src="https://user-images.githubusercontent.com/107904113/187446144-40e5ee2c-6d64-44d9-9f19-fe955af4b84b.png">

**你的思路建议是什么？**
优化

**Comment by harris1943** [comment]
该板块已删除。
