### ISSUE TITLE
系统设置中各个参数没有加校验

### ISSUE THREAD

**Issue by alvin5840** [HummerRisk/HummerRisk#29]
**HummerRisk 版本**
v0.2.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 

**Bug 描述**
如图：当前填写任何信息都可以进行校验，建议对输入内容进行初步校验，比如：地址可以进行IP或者域名的校验，端口应该为纯数字，最大65535

<img width="1482" alt="image" src="https://user-images.githubusercontent.com/107904113/187448283-32a335a9-d67d-4eeb-b7bd-fffa5a1a3720.png">

**Bug 重现步骤(有截图更好)**
1. 进入系统设置
2.参数设置-邮件设置
3.随便输入任何内容，字符串、数字

**Comment by harris1943** [comment]
已完成
