### ISSUE TITLE
hummerrisk:v0.9.0镜像启动失败

### ISSUE THREAD

**Issue by tcsecchen** [HummerRisk/HummerRisk#295]
**HummerRisk 版本**
v0.9.0

**运行方式(安装包运行 or 源码运行 ?)**
一键部署方式

**浏览器版本**
无

**系统版本**
centos 7.9
docker 23.0.1

**严重程度（高、中、低）**
中

**Bug 描述**
使用一键部署方式安装hummerrisk，trivy问题已根据issue #280 进行修复，然后hummer_risk:v0.9.0镜像启动失败，一直restart

**Bug 重现步骤(有截图更好)**
1.
![图片](https://user-images.githubusercontent.com/25191604/218685037-fcd460cc-a1cc-4aeb-a3e1-2d3ea61bd4b0.png)

2.
![图片](https://user-images.githubusercontent.com/25191604/218685267-59ef2510-0396-46f6-80fe-fa1d5b624e44.png)

不是很清楚这个报错是什么，google找了下没找到合适的解决方案

**Comment by harris1943** [comment]
flywaydb报错是指安装hummerrisk的初始化数据报错了，您这边要么是旧的垃圾数据导致的，要么是之前安装失败残留了部分数据，再或者是外部mysql数据库版本在5.7以上。
前两种的解决办法，hrctl uninstall卸载，数据也选择清除 yes。再重新安装就ok了。
最后一种解决办法，连接mysql，执行
SELECT @@SESSION.sql_mode;
set @@SESSION.sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION";

**Comment by tcsecchen** [comment]
感谢，问题已解决~
