### ISSUE TITLE
设置用户密码bug

### ISSUE THREAD

**Issue by colinn66** [HummerRisk/HummerRisk#296]
**HummerRisk 版本**
0.9

**Bug 重现步骤(有截图更好)**
1. 系统设置中修改用户密码，设置为：test1@3$无法设置。
2. 登录页面密码长度不够，只能输入20位密码啊，系统中可以设置30位长度的密码

**Comment by harris1943** [comment]
问题2已解决。
问题1，密码提示 “有效密码：8-30位，英文大小写字母+数字+特殊字符（可选）” 的意思是：
至少8-30个字符，至少1个大写字母，1个小写字母和1个数字，其他特殊字符可以是任意字符
