### ISSUE TITLE
异常日志太多，把存储空间占满

### ISSUE THREAD

**Issue by alvin5840** [HummerRisk/HummerRisk#3]
**HummerRisk 版本**
v0.1.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome 

**Bug 描述**
hummerrisk 的log目录下有个history日志，直接把磁盘占满
<img width="403" alt="image" src="https://user-images.githubusercontent.com/107904113/179380308-9eff03d7-2a35-4a75-b316-69ad77ee3158.png">

**Bug 重现步骤(有截图更好)**
1. 安装
2. 运行任意检测任务
3. 查看日志

**Comment by harris1943** [comment]
已解决，去除无效日志，以及实时翻译带来的巨额log。
