### ISSUE TITLE
源码检测错误

### ISSUE THREAD

**Issue by paddy235** [HummerRisk/HummerRisk#307]
**HummerRisk 版本**

0.9.1

**运行方式(安装包运行 or 源码运行 ?)**

离线内网安装

**浏览器版本**

**严重程度（高、中、低）**

**Bug 描述**

源码检测错误

**Bug 重现步骤(有截图更好)**
1. 
2.
3.

![ksnip_20230217-115514](https://user-images.githubusercontent.com/19899767/219545957-c1d2d176-734a-48ce-95ce-9619fde4c0f3.png)
![ksnip_20230217-115529](https://user-images.githubusercontent.com/19899767/219545970-3a423d76-bfb2-41b8-9c68-f0e0efc59997.png)
![ksnip_20230217-115538](https://user-images.githubusercontent.com/19899767/219545987-91872950-2121-448f-ba80-d1f2807ec4b0.png)

**Comment by paddy235** [comment]
[hummerrisk.logs.tar.gz](https://github.com/HummerRisk/HummerRisk/files/10763085/hummerrisk.logs.tar.gz)

**Comment by paddy235** [comment]
code_result数据库中command字段为空

**Comment by harris1943** [comment]
抱歉，昨天安装的包里面trivy 的 java-db不对劲。需要您重新安装一遍，wget https://company.hummercloud.com/offline-package/hummerrisk/x86_64/hummerrisk-offline-installer-v0.9.1.tar.gz。解压后直接在目录里执行 hrctl upgrade 即可。

**Comment by paddy235** [comment]
每次解压缩完毕，都要在`docker-compose-mysql.yml`中添加

```
    ulimits:
      nproc: 65535
      nofile:
        soft: 26677
        hard: 46677
```

**Comment by paddy235** [comment]
代码扫描可以使用了。

**Comment by paddy235** [comment]
遗憾的是缺少java依赖的漏洞检查

**Comment by harris1943** [comment]
如果是java项目的话，是有java依赖的漏洞检查的啊。
就跟文件检测一样，文件检测可以单独检测pom.xml的。都是trivy实现的，本质没差。
![image](https://user-images.githubusercontent.com/105598469/220216287-d4a6083e-ece5-4a37-8904-736b82316aed.png)
![image](https://user-images.githubusercontent.com/105598469/220216308-8955ad1c-48f1-4e8b-97fe-a0fabbc6885d.png)

**Comment by paddy235** [comment]
对比一下dependency-check和trivy的pom.xml检查结果就知道了，trivy只检查pom.xml当下的，dependency-check深入检查依赖中子依赖的漏洞
