### ISSUE TITLE
云账号列表点击调参按钮后没有规则数据

### ISSUE THREAD

**Issue by wangjiankun233** [HummerRisk/HummerRisk#31]
**HummerRisk 版本**
0.2.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**

**Bug 描述**
云账号列表点击调参按钮后没有规则数据

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by jackie066** [comment]
该问题在下一个版本将会得到解决

**Comment by harris1943** [comment]
已解决
