### ISSUE TITLE
aws是否可以支持BasicSessionCredentials的认证方式

### ISSUE THREAD

**Issue by Ma1tobiose** [HummerRisk/HummerRisk#327]
**HummerRisk 版本**
0.9.1

**你希望我们怎样改进？**
希望aws的认证方式，支持 BasicSessionCredentials 的方式，不只是 BasicAWSCredentials 

**你的思路建议是什么？**
多一个可选方式吧。公司管理需求无法直接创建access_key。用SessionCredentials可以控制有效时间，也会更安全一点

**Comment by alvin5840** [comment]
这是个很好的建议，使用 SessionCredentials 可以尽可能避免AK SK泄露造成的安全风险

**Comment by Ma1tobiose** [comment]
1.0版本已修复
