### ISSUE TITLE
云账号定时检测，保存没反应

### ISSUE THREAD

**Issue by colinn66** [HummerRisk/HummerRisk#333]
**HummerRisk 版本**
0.9.1

云账号定时检查，填完信息后，点保存，页面一直没反应。
![image](https://user-images.githubusercontent.com/107197811/224630160-a74e481b-c17f-45b2-ac26-78bcf815ffe8.png)
关掉弹出页面，回到列表，等了好久会创建出定时任务，但是确实非常久。

**Comment by harris1943** [comment]
该功能在v1.0.0后重新设计
