### ISSUE TITLE
执行部署检测异常 File not found!/opt/hummerrisk/trivy/trivy.json (No such file or directory)

### ISSUE THREAD

**Issue by AsseGhuh** [HummerRisk/HummerRisk#335]
**HummerRisk 0.9.1**

**离线模式安装**

**严重**

**Bug 描述**
执行云原生部署配置检测时，报如下异常
2023-03-14 10:11:30 system 异常: File not found!/opt/hummerrisk/trivy/trivy.json (No such file or directory) File not found!/opt/hummerrisk/trivy/trivy.json (No such file or directory) 

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/40926057/224911219-2f1fa00f-a55d-4423-94c6-92bfa0faa934.png)
![image](https://user-images.githubusercontent.com/40926057/224911273-606f593d-6ee2-4fca-8a31-fc3b9514ac6d.png)

**Comment by harris1943** [comment]
v0.10.0版本已经发布，已经解决此问题，请下载安装尝试，如有问题请反馈。
