### ISSUE TITLE
创建镜像仓库时报500错误: {"status": 500, "error": "Internal Server Error", "path": "/image/addImageRepo/" }

### ISSUE THREAD

**Issue by AsseGhuh** [HummerRisk/HummerRisk#336]
**HummerRisk 版本**
0.9.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
 Chrome 版本 107.0.5304.122（正式版本）

**严重程度（高、中、低）**
高

**Bug 描述**
创建镜像仓库时报500错误： {"status": 500, "error": "Internal Server Error", "path": "/image/addImageRepo/" }

**Bug 重现步骤(有截图更好)**
1.
![1678764174835_0DBED57F-AF26-43de-8C8B-4DE825511EE4](https://user-images.githubusercontent.com/40926057/224912158-9cc6906c-dbac-4fda-9c69-737a2b702671.png)

2.
3.

**Comment by harris1943** [comment]
v0.10.0版本已经发布，已经解决此问题，请下载安装尝试，如有问题请反馈。
