### ISSUE TITLE
k8s 检测中安装日志太多了，希望可以优化

### ISSUE THREAD

**Issue by harold5384** [HummerRisk/HummerRisk#337]
**HummerRisk 版本**
v0.9.1

**你希望我们怎样改进？**
这里的安装日志太多，希望优化一下
<img width="1511" alt="图片" src="https://user-images.githubusercontent.com/117808901/224948281-30fc6576-6575-468e-999d-042f4cfa2a22.png">

**你的思路建议是什么？**
1. 默认只保留3条或者5条
2. 专门做一个系统事件管理的栏目、或消息中心

**Comment by colinn66** [comment]
1.0中减少了消息保留数量，并改为逆序排列，最新的操作在上面
