### ISSUE TITLE
创建部署配置信息，无法批量生成，希望能支持一键同步所有部署配置功能

### ISSUE THREAD

**Issue by asseghuh** [HummerRisk/HummerRisk#340]
**HummerRisk 版本**
0.10.0

**你希望我们怎样改进？**
创建部署配置信息，无法批量生成，希望能支持一键同步所有部署配置功能

**你的思路建议是什么？**

**Comment by alvin5840** [comment]
@AsseGhuh 你现在的配置文件主要都存储在哪里

**Comment by AsseGhuh** [comment]
@alvin5840 配置类型这里，不是有一项"K8S获取YAML内容"吗，然后下面会有一个下拉列表让我选择配置信息。这样的话我必须一个一个选，我这里1000多个的部署，一个一个选太慢了，我的意思就是这个拉列表可不可以做成多选，或者全选。也可以配置类型这里新增一个选项"从k8s获取所有yarn内容，并自动创建所有部署配置信息"。

**Comment by AsseGhuh** [comment]
> @AsseGhuh 你现在的配置文件主要都存储在哪里

存是存在gitLab上的，但是并不是希望做成导入的方式，而是自动从账号里面获取

**Comment by alvin5840** [comment]
@AsseGhuh 这块目前我们正在设计中，后面会支持多种方式：1. 多文本批量导入  2. git 自动同步

**Comment by AsseGhuh** [comment]
@alvin5840 最好是从k8s自动同步，我看你们好像可以单个获取到YAML内容。文本同步和git同步还是不太好管理，我们有1457
 deployments 按业务线放在git各个路径和目录下

**Comment by alvin5840** [comment]
@AsseGhuh git 检测场景在于先扫描，再上线 ，其次可以按照目录分组同步。从k8s同步过来扫描属于“运行时”场景，可以做成多选，这样确实会方便使用一些
