### ISSUE TITLE
自定义云检测规则

### ISSUE THREAD

**Issue by toadzhou** [HummerRisk/HummerRisk#347]
我们需要自定义一些更细致规则，来满足合规部门的要求。
比如
阿里云的REDIS：
1、是否开启了TDE加密，没开启加密则显示为不合规。
2、REDIS是否禁用了指定的高危命令，如flushdb、save等，没禁用则显示为不合规。
3、白名单配置中是否包含"0.0.0.0/0"，如包含则显示为不合规。
阿里去的ECS：
1、访问白名单是不是只包含堡垒机的访问IP(变量控制)，如果除堡垒机以外一白名单，则显示不合规。

**Comment by harris1943** [comment]
阿里云的ECS访问白名单是属于安全组吗

**Comment by toadzhou** [comment]
> 阿里云的ECS访问白名单是属于安全组吗

是的
