### ISSUE TITLE
镜像检测，点击检测后显示成功，但是没有开始检测

### ISSUE THREAD

**Issue by alvin5840** [HummerRisk/HummerRisk#352]
**HummerRisk 版本**
v.0.10

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行 o

**浏览器版本**
chrome

**严重程度（高、中、低）**
高

**Bug 描述**
在“镜像管理”中对创建好的镜像点击执行检测，提示成功，但是在镜像检测结果页面，没有任何检测记录

**Bug 重现步骤(有截图更好)**
<img width="1919" alt="image" src="https://user-images.githubusercontent.com/107904113/227689559-84f1866c-21e8-486c-a5e9-1f1654934f11.png">
<img width="1744" alt="image" src="https://user-images.githubusercontent.com/107904113/227689596-af08479c-49a3-403e-8d90-0e28a9e2483c.png">

**Comment by harris1943** [comment]
图片找不到，导致检测失败。bug
