### ISSUE TITLE
镜像检测，镜像删除后，检测历史记录还在

### ISSUE THREAD

**Issue by alvin5840** [HummerRisk/HummerRisk#353]
**HummerRisk 版本**
v0.10.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome

**严重程度（高、中、低）**
低

**Bug 描述**
镜像检测，镜像删除后，检测历史记录还在，如此以来历史信息会非常多，建议历史数据可以删掉

**Bug 重现步骤(有截图更好)**
1. 创建镜像
2. 执行扫描
3. 删除镜像
4. 查看镜像检测历史记录

**Comment by harris1943** [comment]
所有的检测应该都存在类似问题
