### ISSUE TITLE
客户端不可查询secret key等私密凭证

### ISSUE THREAD

**Issue by iAmSOScArEd** [HummerRisk/HummerRisk#368]
**HummerRisk 版本**
v0.10.0

**你希望我们怎样改进？**
问题：前端任意能够访问到该界面的用户都能查询AK/SK
目标：填写生效后，任何人不能查询该SK，避免SK泄漏
问题路径：混合云安全----多云检测---云账号设置的编辑功能

**你的思路建议是什么？**
1、填写后若云账号生效则前端任意位置不可查询该SK，若不生效可提供SK重填；已生效的不可重填（避免被人覆盖），只能删除。
2、其他位置可填写私密凭证的同理。

**Comment by colinn66** [comment]
已经在新版本中修改，添加时可以看到自己写的内容，修改的时候不会显示之前填写的内容
