### ISSUE TITLE
混合云安全——操作审计，云事件同步错误

### ISSUE THREAD

**Issue by jklZy1** [HummerRisk/HummerRisk#390]
**HummerRisk 版本**
V0.10.0

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
chrome V105.0.5195.102

**严重程度（高、中、低）**
中

**Bug 描述**
混合云安全——操作审计，云事件同步错误
**Bug 重现步骤(有截图更好)**
混合云安全——操作审计，云事件同步，同步**阿里云**的事件信息出现以下报错：
 Error updating database. Cause: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'resource_name' at row 11 ### The error may exist in com/hummerrisk/base/mapper/ext/ExtCloudEventMapper.xml ### The error may involve defaultParameterMap ### The error occurred while setting parameters ### SQL: insert into cloud_event (id,event_id, cloud_account_id, sync_region, acs_region, event_name, event_type, event_category, event_version, event_rw, event_me
![image](https://user-images.githubusercontent.com/34265722/231419516-2e904041-4532-4772-8c2f-f32821766532.png)

**Comment by colinn66** [comment]
已经开始复现和处理了问题
