### ISSUE TITLE
【主机检测】无法添加主机，提示“存在验证失败的虚拟机配置”

### ISSUE THREAD

**Issue by alvin5840** [HummerRisk/HummerRisk#40]
**HummerRisk 版本**
v0.3.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Chrome

**Bug 描述**
![image](https://user-images.githubusercontent.com/107904113/188249295-8892a14f-3971-46f8-9d6e-55dfef5d1665.png)

**Bug 重现步骤(有截图更好)**
1. 创建主机
2. 填写服务器信息，密码和密钥都可以
3. 创建完成后会自动检测，校验失败
4. 手动对主机进行校验，校验失败

**Comment by harris1943** [comment]
已解决
