### ISSUE TITLE
多云监测页面优化，点击检测后遮罩复盖整个页面，必须要等待，无法进行其他操作

### ISSUE THREAD

**Issue by alvin5840** [HummerRisk/HummerRisk#409]
**HummerRisk 版本**
v1.1.0

**你希望我们怎样改进？**
优化

**你的思路建议是什么？**
点击确认后，当前检测的云帐号显示为检测中即可，不用遮罩整个页面等待

<img width="1511" alt="image" src="https://github.com/HummerRisk/HummerRisk/assets/107904113/0f04d9e9-45ee-4482-92cc-fb78e30e7389">

**Comment by harris1943** [comment]
不采纳
