### ISSUE TITLE
主机检测，如果主机是 Linux，不应该可以勾选 Windows 的策略，需要过滤

### ISSUE THREAD

**Issue by alvin5840** [HummerRisk/HummerRisk#412]
**HummerRisk 版本**
v1.1.0

**你希望我们怎样改进？**
加过滤，Windows 显示 Windows的测率，Linux 显示 Linux的策略

**你的思路建议是什么？**
加过滤，Windows 显示 Windows的测率，Linux 显示 Linux的策略
<img width="995" alt="image" src="https://github.com/HummerRisk/HummerRisk/assets/107904113/46a65058-7001-4a0e-b15b-95e99685befe">

**Comment by colinn66** [comment]
收到问题

**Comment by harris1943** [comment]
已解决
