### ISSUE TITLE
一键安装HummerRisk失败

### ISSUE THREAD

**Issue by Fewword** [HummerRisk/HummerRisk#416]
全球版quickstart.sh有问题
_bash: 行 29: 寻找匹配的“"”时遇到了未预期的文件结束符_
中国大陆版docker拉取有问题
_Error response from daemon: pull access denied for hummerrisk/hmr-ui, repository does not exist or may require 'docker login': denied: requested access to the resource is denied_

**Comment by alvin5840** [comment]
问题已经修复，可以试用如下命令重新安装：
```
rm -rf /usr/bin/hrctl 
rm -rf /opt/hummerrisk 
curl -sSL https://download.hummerrisk.com/hummerrisk/hummerrisk/releases/download/latest/quick_start.sh -o quick_start.sh
bash quick_start.sh
```

**Comment by Fewword** [comment]
仍然安装失败
![image](https://github.com/HummerRisk/HummerRisk/assets/76860434/3bb337cc-caf9-4bd1-b153-82aeebbf563a)
