### ISSUE TITLE
hummerrisk-ui 日志一直报499状态码，不能显示登陆表单

### ISSUE THREAD

**Issue by liangkun9400** [HummerRisk/HummerRisk#417]

**Comment by alvin5840** [comment]
@liangkun9400 请详细描述一下你安装的hummerrisk版本、安装方式、使用的浏览器，并提供截图以便于我们发现问题

**Comment by liangkun9400** [comment]
使用的1.0.0版本部署到k8s v1.24.13里面的，但镜像用的1.1.0的，火狐浏览器，截图不方便提供。只能显示登陆页面的背景，没有登陆框，这个问题在重新安装hummerrisk后可以解决，但是如果节点down了重启后，就会出现这个问题

**Comment by alvin5840** [comment]
@liangkun9400 由于提供的错误信息不完整，我们不方便判别是哪里的问题，建议在微信交流群进行沟通
