### ISSUE TITLE
主机检测结果无法下载

### ISSUE THREAD

**Issue by colinn66** [HummerRisk/HummerRisk#426]
**HummerRisk 版本**
V1.10

主机检测结果页面，点下载，之后点PDF和Excel下载都没反应。
![image](https://github.com/HummerRisk/HummerRisk/assets/107197811/e9a4ee6d-80d0-4fd8-bf28-2ab264e83a11)

**Comment by alvin5840** [comment]
收到问题，处理中

**Comment by harris1943** [comment]
已解决
