### ISSUE TITLE
安全漏洞 HummerRisk认证后远程命令执行

### ISSUE THREAD

**Issue by exp1orer** [HummerRisk/HummerRisk#446]
**漏洞影响范围**

v1.1.0-最新版（v1.4.1）

**运行方式(安装包运行 or 源码运行 ?)**

安装包

**严重程度（高、中、低）**

高

**漏洞详情**

漏洞主要位于

`HummerRisk/HummerRisk/hummer-modules/hummer-system/src/main/java/com/hummer/system/service/LicenseService#validateLicense`方法将用户上传的文件内容拼接至验证许可证的命令中。

![image](https://github.com/HummerRisk/HummerRisk/assets/25338973/1e08f576-ca62-4e47-88e9-5ad491187c0b)

而`HummerRisk/HummerRisk/hummer-common/hummer-common-core/src/main/java/com/hummer/common/core/utils/CommandUtils#commonExecCmdWithResultNew`方法拼接命令时使用`sh -c `将字符串参数可作为命令执行。

![image](https://github.com/HummerRisk/HummerRisk/assets/25338973/df422e16-6bd8-40ba-9336-7932a87d1475)

**漏洞复现（最新版本）**

![image](https://github.com/HummerRisk/HummerRisk/assets/25338973/47b6d2ab-5562-4580-9c91-7162016ce372)

命令成功执行

![image](https://github.com/HummerRisk/HummerRisk/assets/25338973/1f48fa5e-7ea5-4a30-9311-61f493a80d67)

**修复建议**

使用安全的调用方式执行`/usr/local/bin/hummer_validator`验证程序，不要将用户输入的内容拼接至`sh -c`的参数中。

**Comment by harris1943** [comment]
HummerRisk后续将所有xpack功能开源开放。license校验功能会移除，api相关接口也会移除。所以此问题后续将不在存在。
