### ISSUE TITLE
【主机检测】-无法通过密钥添加主机，value will not be null

### ISSUE THREAD

**Issue by alvin5840** [HummerRisk/HummerRisk#63]
**HummerRisk 版本**
v0.3.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行 

**浏览器版本**
chrome

**严重程度（高、中、低）**
高

**Bug 描述**
采用密钥登录，应该可以不输入密码，“value will not be null” 告警提示很不友好，不知道是哪里填写有问题
<img width="1223" alt="image" src="https://user-images.githubusercontent.com/107904113/190047879-4cb4ed59-6a57-4c32-88eb-93bc5ff056fc.png">

**Bug 重现步骤(有截图更好)**
1.主机检测-主机管理-添加主机
2.填写ip、用户名、端口，采用密钥登录，不填写密码
3.确定提交

**Comment by harris1943** [comment]
添加了统一凭证功能，已完成
