### ISSUE TITLE
【公有云扫描】无法进行快速检测

### ISSUE THREAD

**Issue by alvin5840** [HummerRisk/HummerRisk#69]
**HummerRisk 版本**
v0.3.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome

**严重程度（高、中、低）**
高

**Bug 描述**
点击快速检测，请求一直pending

<img width="1915" alt="image" src="https://user-images.githubusercontent.com/107904113/190848510-3636220f-4aed-4e3c-ba52-7f3cc5b4824c.png">

**Bug 重现步骤(有截图更好)**
1.创建云账户
2.运行检测

**Comment by harris1943** [comment]
已做初步优化，待进一步优化

**Comment by harris1943** [comment]
已解决
