### ISSUE TITLE
合规报告结果搜索错误

### ISSUE THREAD

**Issue by alvin5840** [HummerRisk/HummerRisk#88]
**HummerRisk 版本**
v0.3.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome

**严重程度（高、中、低）**
中

**Bug 描述**
包括结果搜索 “有风险”，过滤不出来有风险的列表
<img width="1509" alt="image" src="https://user-images.githubusercontent.com/107904113/191756950-ba459ed4-0a60-49c4-8d58-5a6890888a5a.png">
执行搜索后，结果都没了
<img width="1508" alt="image" src="https://user-images.githubusercontent.com/107904113/191757019-53a37825-eaa7-4d96-a638-bc30c9cc0fdc.png">

**Bug 重现步骤(有截图更好)**
1. 混合云安全-绑定云账户-执行扫描
2. 查看扫描结果
3. 搜索过滤扫描报告

**Comment by harris1943** [comment]
已完成
