### ISSUE TITLE
主机检测中的凭据可以直接查看密码，太不安全了，建议加密或者不显示

### ISSUE THREAD

**Issue by alvin5840** [HummerRisk/HummerRisk#89]
**HummerRisk 版本**
v0.3.2

**你希望我们怎样改进？**
如图：ssh的凭据可以直接查看密码，太不安全了，最好加密显示然后通过某种安全机制解密显示，或者不显示

<img width="1511" alt="image" src="https://user-images.githubusercontent.com/107904113/191759231-98020b8b-75f0-4447-ac60-a7d0e7fafce6.png">

**你的思路建议是什么？**
加密或隐藏

**Comment by harris1943** [comment]
用户看这里就是为了快速查看密钥或密码是啥，是啥最快速的获取方式。加密毫无意义，所以无需处理
