### ISSUE TITLE
检测的规则只能设置一个标签吗

### ISSUE THREAD

**Issue by zbhlove100** [HummerRisk/HummerRisk#9]
检测的规则只能设置一个标签吗，可以设置多个标签吗

**Comment by harris1943** [comment]
您好，为了不影响用户使用混乱，目前规则只支持一个标签。标签是为了统计更方便的使用项。
因为像混合云检测，执行检测规则是按规则组进行检测的，规则组和风险条例是可以设置多个的。
希望这样的回答能让您满意。
