### ISSUE TITLE
【主机检测】创建的主机凭据无法选择

### ISSUE THREAD

**Issue by alvin5840** [HummerRisk/HummerRisk#90]
**HummerRisk 版本**
v0.3.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome

**严重程度（高、中、低）**
高

**Bug 描述**
创建的主机凭据看不到
<img width="1500" alt="image" src="https://user-images.githubusercontent.com/107904113/191760424-18f73f78-83d6-43d9-9e57-bde222da1f1c.png">

<img width="1315" alt="image" src="https://user-images.githubusercontent.com/107904113/191760188-839a0681-d88d-4a32-b688-c07d565e6c30.png">

**Bug 重现步骤(有截图更好)**
1. 主机检测
2. 创建凭据
3. 主机管理-创建主机-选择凭据

**Comment by harris1943** [comment]
bug， 数据未及时刷新

**Comment by harris1943** [comment]
已解决
