### ISSUE TITLE
Bug: SBOM检测完，看不到检查结果

### ISSUE THREAD

**Issue by alvin5840** [HummerRisk/HummerRisk#92]
**HummerRisk 版本**
v0.3.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome

**严重程度（高、中、低）**
高

**Bug 描述**
如图：执行完检测任务，去查看检测结果，里面没有内容
<img width="1507" alt="image" src="https://user-images.githubusercontent.com/107904113/191762903-78d899ce-3747-4599-82c9-61837cf1f1a5.png">
<img width="1484" alt="image" src="https://user-images.githubusercontent.com/107904113/191762956-1242b12b-a5c6-4f32-9a36-89652fb051c0.png">

**Bug 重现步骤(有截图更好)**
1. SBOM 管理
2. 创建项目-关联镜像
3. 执行检测

**Comment by harris1943** [comment]
已解决
