### ISSUE TITLE
源码检测结果打开后，无法关闭，点击按钮无反应

### ISSUE THREAD

**Issue by alvin5840** [HummerRisk/HummerRisk#93]
**HummerRisk 版本**
v0.3.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome

**严重程度（高、中、低）**
高

**Bug 描述**
下图中的关闭按钮，无法点击，无法关闭
<img width="1511" alt="image" src="https://user-images.githubusercontent.com/107904113/191764385-86a6d985-46c3-48b2-a04c-cdedd1a03702.png">

<img width="1298" alt="image" src="https://user-images.githubusercontent.com/107904113/191764682-c9b07d1c-1e89-4d84-84c1-05991a28fa13.png">

**Bug 重现步骤(有截图更好)**
1. 源码检测-关联github仓库地址
2. 执行检测
3. 应该是没检测完，点击看结果，页面就可以打开了，然后无法关闭

建议结果没出来之前，查看按钮为不可点击状态吧

**Comment by harris1943** [comment]
<img width="1297" alt="image" src="https://user-images.githubusercontent.com/105598469/191818972-e7785525-a578-4518-ada0-1f28580bd2f8.png">
无法复现此问题，系旧版本， 执行状态可以点击，因为内置执行状态，可以滚动显示执行过程。
