### ISSUE TITLE
源码检测没有结果 Unexpected end of JSON input

### ISSUE THREAD

**Issue by alvin5840** [HummerRisk/HummerRisk#95]
**HummerRisk 版本**
v0.3.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 

**严重程度（高、中、低）**
高

**Bug 描述**
如图，检测状态是”已完成“，但是没有任何检测结果
<img width="1307" alt="image" src="https://user-images.githubusercontent.com/107904113/191769600-9613b5da-2591-43d6-a918-9be95ea6293d.png">

<img width="1511" alt="image" src="https://user-images.githubusercontent.com/107904113/191769110-826b329c-4913-421d-b90c-2f0b7951c3b4.png">

**Bug 重现步骤(有截图更好)**
1. 源码检测-创建项目-绑定github项目地址
2. 执行检测-等待检测完成后查看结果
3.  查看结果

**Comment by harris1943** [comment]
系旧版本
